### ISSUE TITLE
Add Connection Aggregate

### ISSUE THREAD

**Issue by nanderstabel** [impierce/ssi-agent#125]
### Description

Add Connection Aggregate to UniCore.

This new aggregate needs to be added to the upcoming `agent_identity` domain and serves as a container for the agent's connections/entities with whom it has/will interact.

The aggregate needs to contain at least:
- it's own ID
- optional domain of the connection
- optional DID of the connection
- TBD

`POST`, `GET` and `DELETE` methods endpoints need to be added to a new `/v0/identity/connections` endpoint in `agent_api_rest`

The `connection_id` needs to be added to other aggregates:
- `Offer` (both issuance and holder)
- `Credential` (both issuance and holder)
- possibly more

### Motivation

This will enable management of the relationships and interactions between UniCore and other entities.

### Resources

n/a

### To-do List

- [ ] Add `Connection` aggregate
- [ ] Add `connection_id` to other aggregates
- [ ] Add `/v0/identity/connections` endpoint

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Connection Aggregate](https://trello.com/c/N2q5TRxh/23-add-connection-aggregate)
