### ISSUE TITLE
feat: add PresentationDefinitionId's

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/ssi-agent#139]
### Description

Currently we have our PresentationDefinitions (PD) hardcoded in `agent_verification/presentation_definitions/presentation_definition.json` and in our postman collection.

In the future we want to work PDId's in (most of) our API interactions. This will be much cleaner and easier for external parties to use and more scalable.

### Motivation

Makes working with PD's much smoother and also aligns with other parties in our field

### To-do List

- [ ] We need a seperate table in our postgresql database of key-value pairs of PDId's and there PD's.
- [ ] Aggregates must be added to maintain this data domain.
- [ ] API's must be added along with their adapters and commands to be able to interact with the database, to fetch, add or delete a PD.
- [ ] These actions need to publish events
- [ ] Existing code must be update to work with PDId's instead of directly with PD's.

**Comment by nanderstabel** [comment]
Related: https://github.com/impierce/ssi-agent/issues/100

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [feat: add PresentationDefinitionId's](https://trello.com/c/Nn6W8gqu/31-feat-add-presentationdefinitionids)
