### ISSUE TITLE
Add support for `did:iota` identities

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/ssi-agent#17]
### Description

Add support for the `did:iota` method to the ssi-agent. The agent should be able to create, destroy and verify identities using the `did:iota` method, from the perspective of all 3 roles: Issuer, Holder and Verifier. Due to the nature of the `did:iota` method, this functionality requires the agent to generate an iota (and SMR & RMS) address to which tokens can be deposited. The address must not be tied to the identity yet, as it could be considered a wallet from which multiple identities can be funded. Once created, the identity must be stored and be re-instantiated if the agent is turned off and on. Due to the need for real funding, the identities must be properly destroyed on reset. Updating identities with key rotation is out-of-scope of the current issue. 

### Motivation

Using IOTA technology greatly enhances future capabilities of the agent. It would increase privacy for the Holders, allow on-chain revocation lists, key rotation, public credentials and much more. All worldwide accessible with 100% guaranteed data-availability and uptime in a decentralized manner. 

### Resources

- [Iota Implementation](https://github.com/iotaledger/identity.rs/tree/main/identity_iota)
- [DID method](https://wiki.iota.org/identity.rs/references/specifications/iota-did-method-spec/)

### To-do List

- [ ] Generate IOTA,SMR,RMS addresses from appropriate keys and store the keys in a Stronghold.
- [ ] Have a method to export IOTA, SMR, RMS tokens back to an address outside the control of the agent
- [ ] Add default node list in settings file for IOTA, SMR and RMS networks
- [ ] Generate `did:iota` identity on appropriate network (IOTA, SMR, RMS)
- [ ] Destroy `did:iota` and return funds to controlled address
- [ ] Enable signing credentials with `did:iota`
- [ ] Implement `did:iota` verification

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for did:iota identities](https://trello.com/c/j4JzYPry/1-add-support-for-didiota-identities)
