### ISSUE TITLE
Add support for `did:web`

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/ssi-agent#18]
### Description

Add support for the `did:web` method. The agent should be able to create, destroy and verify identities using the `did:web` method, from the perspective of all 3 roles: Issuer, Holder and Verifier. Once created, the identity must be stored and be re-instantiated if the agent is turned off and on.

### Motivation

One step closer to full compatibility with the Dutch Blockchain Coalition's DIIP profile.

### Resources

- [DIIP Profile](https://github.com/DutchBlockchainCoalition/DIIP/discussions/12)
- [DID method](https://w3c-ccg.github.io/did-method-web/)

### To-do List

- [x] Find existing `did:web` crate in Rust (or don't and implement the method separately)
- [x] Implement `did:web` as another method option
- [x] Add verification of `did:web` method
