### ISSUE TITLE
Add Persistent and Temporary mode for managing secrets

### ISSUE THREAD

**Issue by nanderstabel** [impierce/ssi-agent#41]
### Description

We use a `SecretManager` for managing secrets in both `agent_issuance` and `agent_verification`. Under the hood, the `SecretManager` uses a Stronghold file where the secrets are actually stored. We need to be able to properly support 3 scenario's:
- Temporary Mode: the UniCore consumer does not supply their own Stronghold file. On spin-up UniCore will generate a new Stronghold file that the `SecretManager` will utilize. The Stronghold file will be lost once the docker container is stopped.
- Persistent Mode with external Stronghold: the UniCore consumer supplies their own Stronghold file that the `SecretManager` will utilize.
- Persistent Mode without external Stronghold:  the UniCore consumer does not supply their own Stronghold file. On first spin-up UniCore will generate a new Stronghold file which can be reused.

### Motivation

Support different use cases:
- For simple testing
- For self management of secrets
- For dynamic secret management

### Resources

n/a

### To-do List

- [ ] Support Temporary Mode
- [ ] Support Persistent Mode (dynamic)
- [ ] Support Temporary Mode with external Stronghold (static)

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Persistent and Temporary mode for managing secrets](https://trello.com/c/lBFWqHGL/9-add-persistent-and-temporary-mode-for-managing-secrets)

**Comment by berkes** [comment]
To add some "nice to haves" for us, based on the following issues we encounter:

- Generating the stronghold file is -by design- CPU and memory intensive. In e.g. k8s that means we need to allocate a lot of CPU and Mem to the pods, only for the initial generation of the stronghold file
- Generating the initial file takes long (>5 minutes) which is not a problem, but that means we need to set the "health check" to very long values, again, only for the initial generation of the file.

We'd like generate the stronghold file for "dev" and "test" in an init-container. 
We'd like to provide the stronghold file for prod, acc etc.

**Ideally, a separate "secret-manager" binary that will only create a stronghold file based on the application config (yaml/env) and nothing more, would be ideal.**

Then an init container can run this and dynamically generate this file as needed.
And for stable environments, we can run this command once, and then store the result in some secret-management that will set this as (read-only?) file on our pods.
