### ISSUE TITLE
Domain Linkage

### ISSUE THREAD

**Issue by daniel-mader** [impierce/ssi-agent#73]
### Description

UniCore should produce a [Domain Linkage Credential](https://identity.foundation/.well-known/resources/did-configuration/#domain-linkage-credential) and host a [DID Configuration Resource](https://identity.foundation/.well-known/resources/did-configuration/#DIDConfigurationResource) under the [.well-known](https://identity.foundation/.well-known/resources/did-configuration/#did-configuration-uri) endpoint.

### Resources

- [DID Configuration Resource](https://identity.foundation/.well-known/resources/did-configuration/#did-configuration-resource)
- [Linked Domain Service Endpoint](https://identity.foundation/.well-known/resources/did-configuration/#linked-domain-service-endpoint)

### To-do List

- [ ] Produce [Domain Linkage Credential](https://identity.foundation/.well-known/resources/did-configuration/#domain-linkage-credential) on startup
- [ ] Create a [DID Configuration Resource](https://identity.foundation/.well-known/resources/did-configuration/#DIDConfigurationResource)
- [ ] Make it available at `/.well-known/did-configuration.json`
