### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by daniel-mader** [impierce/ssi-agent#96]
### Description

We want to follow [Semantic Versioning 2.0.0](https://semver.org/) to release new versions of UniCore. This should happen in an automated way (through a GitHub Action) and produce predictable results.

The following is desired:

- [ ] enforced conventional commits
- [x] PR titles are linted against the same ruleset (since squash commits are the default)
- [x] a new release pipeline is triggered manually that collects all commits since the last release and builds and publishes a new release automatically
- [ ] a CHANGELOG is updated
- [ ] a new Docker image is published to DockerHub

### To-do List

**Open questions**

- [ ] Do we want to enforce conventional commit messages locally (through `.husky`) or only check the PR title?
- [ ] Which conventional commit style should we follow? `config-conventional` or `config-angular`?

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Semantic Versioning](https://trello.com/c/6EOeoVr0/15-semantic-versioning)
